help_categories = {
    
    # General (0)
    "0.0.0.0.0" : "General",
    # Food & Essentials (1)
    "1": "Food & Essentials",
    "1.1.A": "Preferred Meal Type",
    "1.1.B": "Dietary Restrictions",
    "1.1.C": "Household Size",
    "1.2.A": "Grocery List",
    "1.2.B": "Delivery Address",
    "1.2.C": "Preferred Time",
    "1.2.D": "Payment Method",
    "1.3.A": "Cooking Task",
    "1.3.B": "Recipe Preference",
    "1.3.C": "Kitchen Equipment",

    # Clothing (2)
    "2": "Clothing Support",
    "2.1.A": "Category",
    "2.1.B": "Size",
    "2.1.C": "Condition",
    "2.1.D": "Image",
    "2.1.E": "Location",
    "2.1.F": "Drop or Pickup",
    "2.2.A": "Item Name",
    "2.2.B": "Category",
    "2.2.C": "Size",
    "2.2.D": "Condition",
    "2.2.E": "Quantity",
    "2.2.F": "Image",
    "2.2.G": "Request Type",
    "2.2.H": "Pickup Datetime",
    "2.3.1.A": "Num Adults",
    "2.3.1.B": "Num Children",
    "2.4.A": "Alert Type",
    "2.4.B": "Size",
    "2.4.C": "Date Range",
    "2.5.A": "Garment Details",
    "2.5.B": "Images",
    "2.5.C": "Delivery Method",

    # Housing (3)
    "3": "Housing Assistance",
    "3.1.A": "City/Zip Code",
    "3.1.B": "Rent Range",
    "3.1.C": "Property Type",
    "3.1.D": "House Type",
    "3.1.E": "Agreement Type",
    "3.1.F": "Roommate Preferences",
    "3.1.G": "Additional Room Criteria",
    "3.1.H": "Availability Timeline",
    "3.2.A": "Document Uploaded",
    "3.2.B": "Help Type",
    "3.2.C": "Concerns",
    "3.2.D": "Urgency",
    "3.3.A": "Item Type",
    "3.3.B": "Listing Link",
    "3.4.A": "Move-in Address",
    "3.4.B": "Support Type",
    "3.4.C": "Special Needs",
    "3.4.D": "Num Helpers",
    "3.4.E": "Time Slot",
    "3.5.A": "Cleaning Area",
    "3.5.B": "Cleaning Type",
    "3.6.A": "Repair Type",
    "3.6.B": "Issue Description",
    "3.7.A": "Utility Type",
    "3.7.B": "Move-in Date",
    "3.7.C": "Location",

    # Education (4)
    "4": "Education & Career Support",
    "4.1.A": "Application Area",
    "4.1.B": "Uploaded Documents",
    "4.1.C": "Preferred Timeline",
    "4.2.A": "Document Type",
    "4.2.B": "Feedback Type",
    "4.2.C": "Deadline",
    "4.3.A": "Subject",
    "4.3.B": "Grade Level",
    "4.3.C": "Tutoring Mode",
    "4.3.D": "Availability",

    # Healthcare (5)
    "5": "Healthcare & Wellness",
    "5.1.A": "Location",
    "5.1.B": "Urgency Level",
    "5.1.C": "Accessibility Needs",
    "5.1.D": "Consultation Method",
    "5.2.A": "Delivery Type",
    "5.2.B": "Item List",
    "5.2.C": "Address",
    "5.2.D": "Delivery Time",
    "5.3.A": "Help Type",
    "5.3.B": "Appointment Method",
    "5.3.C": "Zip Code",
    "5.3.D": "Provider Type",
    "5.4.A": "Reminder Method",
    "5.4.B": "Reminder Time",
    "5.4.C": "Repetition Schedule",
    "5.4.D": "Duration",
    "5.5.A": "Education Topic",
    "5.5.B": "Preferred Format",

    # Elderly (6)
    "6": "Elderly & Community Support",
    "6.1.A": "Preferred Location",
    "6.1.B": "Budget Range",
    "6.1.C": "Facility Type",
    "6.1.D": "Move Timeline",
    "6.1.E": "Amenities",
    "6.1.F": "Move Date",
    "6.1.G": "Move Address",
    "6.1.H": "Destination Address",
    "6.1.I": "Items to Move",
    "6.1.J": "Assistance Type",
    "6.2.A": "Device Type",
    "6.2.B": "Device Brand",
    "6.2.C": "Tech Help Type",
    "6.3.A": "Medication Count",
    "6.3.B": "Reminder Type",
    "6.3.C": "Setup Mode",
    "6.3.D": "Health Device Type",
    "6.4.A": "Errand Type",
    "6.4.B": "Pickup Location",
    "6.4.C": "Delivery Location",
    "6.4.D": "Trip Type",
    "6.4.E": "Transport Mode",
    "6.4.F": "Accessibility Needs",
    "6.4.G": "Appointment Type",
    "6.4.H": "Scheduling Mode",
    "6.5.A": "Social Activity",
    "6.5.B": "Social Frequency",
    "6.6.A": "Meal Help Type",
    "6.6.B": "Meal Location",
    "6.6.C": "Dietary Preferences",
    "6.6.D": "Meal Schedule",
}