TAXONOMY = {
    # General
    "GENERAL_CATEGORY": "General or uncategorized assistance requests.",

    # Food & Essentials
    "FOOD_AND_ESSENTIALS": "Parent category for all food and basic essentials-related assistance.",
    "FOOD_ASSISTANCE": "Help users find food banks, pantries, and government meal programs.",
    "GROCERY_SHOPPING_AND_DELIVERY": "Request help with grocery shopping and doorstep delivery by volunteers.",
    "COOKING_HELP": "Users can request help from volunteers to assist with basic cooking and kitchen tasks.",
    "MEAL_PREP_BASIC": "Assistance with basic meal preparation and simple cooking.",
    "FESTIVE_OR_BULK_COOKING": "Help with cooking for festivals, events, or bulk meal preparation.",
    "NUTRITIONAL_MEAL_PLANNING": "Guidance on nutritious meal planning and balanced diets.",
    "CULTURAL_CUISINE_GUIDANCE": "Help with preparing or understanding specific cultural or traditional cuisines.",
    "OTHER_COOKING_HELP": "Other cooking-related assistance not covered by the above.",

    # Clothing
    "CLOTHING_ASSISTANCE": "Parent category for all clothing-related assistance and services.",
    "DONATE_CLOTHES": "Allow users (donors) to donate clothes based on their location.",
    "BORROW_CLOTHES": "Allow users to borrow clothes easily via the platform.",
    "EMERGENCY_CLOTHING_ASSISTANCE": "Enable users in crisis situations (e.g., natural disasters, sudden displacement) to request clothing help.",
    "TAILORING": "Users can request clothing repair (e.g., seams, zippers) via volunteers or local tailoring partners.",

    # Housing
    "HOUSING_ASSISTANCE": "Parent category for all housing-related assistance and services.",
    "LEASE_SUPPORT": "Assistance understanding or navigating lease agreements and landlord matters.",
    "TENANT_RENT_SUPPORT": "Support with rent-related issues, tenant rights, and rental affordability.",
    "REPAIR_MAINTENANCE_SUPPORT": "Support for home repairs and maintenance tasks.",
    "PLUMBING": "Plumbing repairs, leaks, and fixture installation or repair.",
    "HANDYMAN": "General handyman tasks and small fixes around the home.",
    "ELECTRICIAN": "Electrical repairs, wiring, and fixture installation.",
    "CARPENTRY": "Carpentry work including furniture repair and basic woodwork.",
    "GARDEN": "Garden maintenance, landscaping, and outdoor upkeep.",
    "HVAC_AIR_CONDITIONING": "Heating, ventilation, and air conditioning repair or maintenance.",
    "ROOFING": "Roof repair, inspection, and maintenance.",
    "LOCKSMITH": "Lock repair, key duplication, and security hardware.",
    "PAINTING": "Interior or exterior painting and touch-ups.",
    "MASONRY_OR_CONCRETE": "Masonry, concrete work, and structural repairs.",
    "METALWORK_OR_WELDING": "Metalwork, welding, and metal repair.",
    "POOL_AND_SPA_MAINTENANCE": "Pool and spa cleaning, repair, and maintenance.",
    "OTHER_REPAIR_MAINTENANCE_SUPPORT": "Other repair or maintenance not listed above.",
    "UTILITIES_SETUP_SUPPORT": "Assistance setting up internet, electricity, water, and other services during move-in.",
    "LOOKING_FOR_RENTAL": "Help finding rental listings and suitable housing.",
    "FIND_ROOMATE": "Help users find compatible roommates by posting listings or providing guidance.",
    "MOVE_IN_HELP": "In-person support for packing, sorting, or organizing during a move.",
    "BOOKING_PACKERS_MOVERS_SUPPORT": "Assistance booking or coordinating packers and movers.",
    "BUY_THINGS": "Help buying secondhand or new furniture and home essentials.",
    "SELL_THINGS": "Help selling furniture, household items, or other belongings.",

    # Education & Career
    "EDUCATION_CAREER_SUPPORT": "Parent category for education and career-related help.",
    "COLLEGE_APPLICATION_HELP": "Guidance for navigating college application tasks.",
    "SOP_ESSAY_REVIEW": "Review and feedback on SOPs, essays, and academic statements.",
    "TUTORING": "Academic tutoring for specific subjects or standardized tests.",
    "MATH": "Tutoring in mathematics.",
    "ENGLISH": "Tutoring in English language and literature.",
    "SCIENCE": "Tutoring in science subjects (e.g., physics, chemistry, biology).",
    "COMPUTER_SCIENCE": "Tutoring in computer science and programming.",
    "TEST_PREP": "Standardized test preparation (e.g., SAT, GRE, GMAT).",
    "OTHER_SUBJECTS": "Tutoring in other subjects not listed above.",
    "SCHOLARSHIP_KNOWLEDGE": "Information and guidance on scholarships and financial aid.",
    "STUDY_GROUP_FORMATION": "Help forming or joining study groups.",
    "CAREER_GUIDANCE": "Career advice, resume review, and job search support.",
    "EDUCATION_RESOURCE_SHARING": "Sharing or finding educational resources (books, notes, materials).",

    # Healthcare & Wellness
    "HEALTHCARE_AND_WELLNESS": "Parent category for health-related assistance and non-clinical wellness support.",
    "MEDICAL_CONSULTATION": "General or specialty medical consultation and guidance.",
    "GENERAL_CONSULTATION": "General health consultation and advice.",
    "ENT(EAR_NOSE_AND_THROAT)": "Ear, nose, and throat (ENT) related consultation.",
    "DENTAL_OR_ORAL_HEALTH": "Dental and oral health consultation and guidance.",
    "EYE_OR_VISION_CARE": "Eye care and vision-related consultation.",
    "CARDIAC_OR_BLOOD_PRESSURE": "Cardiac health and blood pressure related guidance.",
    "ORTHOPEDIC_OR_PHYSIOTHERAPY": "Orthopedic or physiotherapy related advice.",
    "SKIN_OR_DERMATOLOGY": "Skin and dermatology related consultation.",
    "WOMENS_OR_REPRODUCTIVE_HEALTH": "Women's health and reproductive health guidance.",
    "VACCINATIONS_AND_PREVENTIVE_SCREENINGS": "Information on vaccinations and preventive health screenings.",
    "PEDIATRICS_OR_CHILD_HEALTH": "Pediatric and child health related consultation.",
    "OTHER_MEDICAL_CONCERN": "Other medical concerns not listed above.",
    "MEDICINE_DELIVERY": "Assist with OTC medication pickup or pharmacy navigation.",
    "MENTAL_WELLBEING_SUPPORT": "Access general mental health resources or referrals.",
    "MEDICATION_REMINDERS": "Set up non-clinical reminders for OTC medication or supplements.",
    "HEALTH_EDUCATION_GUIDANCE": "Wellness awareness on hygiene, sleep, nutrition, etc.",

    # Elderly & Community
    "ELDERLY_COMMUNITY_ASSISTANCE": "Parent category for elderly and community-related support.",
    "SENIOR_RELOCATION_SUPPORT": "Help seniors find housing and assist with the moving process.",
    "DIGITAL_SUPPORT_FOR_SENIORS": "Support with using phones, tablets, and apps.",
    "MEDICATION_MANAGEMENT": "Medication reminders or help organizing medications (non-clinical).",
    "MEDICAL_DEVICES_SETUP": "Help setting up or using medical devices at home (non-clinical).",
    "ERRANDS_EVENTS_TRANSPORTATION": "Assistance with errands or transport to events.",
    "TRANSPORTATION_APPOINTMENTS_EVENTS": "Transport to appointments, events, or other destinations.",
    "SCHEDULING_APPOINTMENTS_OR_TASKS": "Help scheduling appointments or organizing tasks.",
    "SOCIAL_CONNECTION": "Companionship and social activities (calls, walks, games).",
    "MEAL_SUPPORT": "Help cooking meals or prepping food based on dietary needs.",
}
