TAXONOMY = {
    # General
    "GENERAL_CATEGORY": "Use only for requests that are truly unclear or do not fit any defined support area. Do not use when the request is clearly about health, emotional support, education, housing, food, clothing, or elderly assistance.",
    # Food & Essentials
    "FOOD_AND_ESSENTIALS": "Parent category for all food and basic essentials-related assistance.",
    "FOOD_ASSISTANCE": "Help users find food banks, pantries, and government meal programs.",
    "GROCERY_SHOPPING_AND_DELIVERY": "Request help with grocery shopping and doorstep delivery by volunteers.",
    "COOKING_HELP": "Users can request help from volunteers to assist with basic cooking and kitchen tasks.",
    "MEAL_PREP_BASIC": "Assistance with basic meal preparation and simple cooking.",
    "FESTIVE_OR_BULK_COOKING": "Help with cooking for festivals, events, or bulk meal preparation.",
    "NUTRITIONAL_MEAL_PLANNING": "Guidance on nutritious meal planning and balanced diets.",
    "CULTURAL_CUISINE_GUIDANCE": "Help with preparing or understanding specific cultural or traditional cuisines.",
    "OTHER_COOKING_HELP": "Other cooking-related assistance not covered by the above.",
    # Clothing
    "CLOTHING_ASSISTANCE": "Parent category for all clothing-related assistance and services.",
    "DONATE_CLOTHES": "Use when the user offers to donate or give away clothes.",
    "BORROW_CLOTHES": "Use when the user needs clothes for themselves or family.",
    "EMERGENCY_CLOTHING_ASSISTANCE": "Use when urgent clothing is needed due to crisis or displacement.",
    "TAILORING": "Use for clothing repairs like seams, zippers, or alterations.",
    # Housing
    "HOUSING_ASSISTANCE": "Parent category for all housing-related assistance and services.",
    "LEASE_SUPPORT": "Assistance understanding or navigating lease agreements and landlord matters.",
    "TENANT_RENT_SUPPORT": "Support with rent-related issues, tenant rights, and rental affordability.",
    "REPAIR_MAINTENANCE_SUPPORT": "Support for home repairs and maintenance tasks.",
    "PLUMBING": "Plumbing repairs, leaks, and fixture installation or repair.",
    "HANDYMAN": "General handyman tasks and small fixes around the home.",
    "ELECTRICIAN": "Electrical repairs, wiring, and fixture installation.",
    "CARPENTRY": "Carpentry work including furniture repair and basic woodwork.",
    "GARDEN": "Garden maintenance, landscaping, and outdoor upkeep.",
    "HVAC_AIR_CONDITIONING": "Heating, ventilation, and air conditioning repair or maintenance.",
    "ROOFING": "Roof repair, inspection, and maintenance.",
    "LOCKSMITH": "Lock repair, key duplication, and security hardware.",
    "PAINTING": "Interior or exterior painting and touch-ups.",
    "MASONRY_OR_CONCRETE": "Masonry, concrete work, and structural repairs.",
    "METALWORK_OR_WELDING": "Metalwork, welding, and metal repair.",
    "POOL_AND_SPA_MAINTENANCE": "Pool and spa cleaning, repair, and maintenance.",
    "OTHER_REPAIR_MAINTENANCE_SUPPORT": "Other repair or maintenance not listed above.",
    "UTILITIES_SETUP_SUPPORT": "Assistance setting up internet, electricity, water, and other services during move-in.",
    "LOOKING_FOR_RENTAL": "Help finding rental listings and suitable housing.",
    "FIND_ROOMATE": "Help users find compatible roommates by posting listings or providing guidance.",
    "MOVE_IN_HELP": "In-person support for packing, sorting, or organizing during a move.",
    "BOOKING_PACKERS_MOVERS_SUPPORT": "Assistance booking or coordinating packers and movers.",
    "BUY_THINGS": "Help buying secondhand or new furniture and home essentials.",
    "SELL_THINGS": "Help selling furniture, household items, or other belongings.",
    # Education & Career
    "EDUCATION_CAREER_SUPPORT": "Parent category for school, college, academics, tutoring, scholarships, study resources, resumes, interviews, and job or career development. Do not use for general health, wellness, emotional support, or medical guidance.",
    "COLLEGE_APPLICATION_HELP": "Guidance for navigating college application tasks.",
    "SOP_ESSAY_REVIEW": "Review and feedback on SOPs, essays, and academic statements.",
    "TUTORING": "Academic tutoring for specific subjects or standardized tests.",
    "MATH": "Tutoring in mathematics.",
    "ENGLISH": "Tutoring in English language and literature.",
    "SCIENCE": "Tutoring in science subjects (e.g., physics, chemistry, biology).",
    "COMPUTER_SCIENCE": "Tutoring in computer science and programming.",
    "TEST_PREP": "Standardized test preparation (e.g., SAT, GRE, GMAT).",
    "OTHER_SUBJECTS": "Tutoring in other subjects not listed above.",
    "SCHOLARSHIP_KNOWLEDGE": "Information and guidance on scholarships and financial aid.",
    "STUDY_GROUP_FORMATION": "Help forming or joining study groups.",
    "CAREER_GUIDANCE": "Use for career advice, resume review, interview preparation, networking, and job search support. Do not use for health advice, wellness questions, or emotional support.",
    "EDUCATION_RESOURCE_SHARING": "Use for sharing or finding academic learning resources such as books, notes, courses, and study materials. Do not use for health tips, sleep guidance, or medical information.",
    # Healthcare & Wellness
    "HEALTHCARE_AND_WELLNESS": "Parent category for health-related assistance, including physical symptom evaluation, medical consultation, preventive care questions, health and wellness guidance, and emotional or mental wellbeing support.",
    "MEDICAL_CONSULTATION": "Use for physical symptoms, pain, injury, body-part complaints, mobility issues, or requests to consult a doctor or medical specialist. Includes both general and specialty medical evaluation; not for emotional support or general wellness education.",
    "GENERAL_CONSULTATION": "Use for non-specific physical symptoms or general health concerns that need an initial medical evaluation by a doctor, including flu-like or mixed symptoms such as fever, fatigue, body aches, and sore throat when no specific specialty is clearly primary.",
    "ENT(EAR_NOSE_AND_THROAT)": "Use for clearly localized ear, nose, sinus, or throat complaints, or requests to see an ENT specialist. Do not use when the request is mainly about broad flu-like or whole-body illness without a clearly primary ENT issue.",
    "DENTAL_OR_ORAL_HEALTH": "Dental and oral health consultation and guidance.",
    "EYE_OR_VISION_CARE": "Use for blurred vision, eye pain, eye strain, watering, discomfort, trouble seeing, or requests to consult an eye doctor or vision specialist.",
    "CARDIAC_OR_BLOOD_PRESSURE": "Cardiac health and blood pressure related guidance.",
    "ORTHOPEDIC_OR_PHYSIOTHERAPY": "Use for joint, muscle, bone, back, neck, shoulder, arm, leg, or mobility problems, including stiffness, injury, rehabilitation, and physiotherapy or orthopedic evaluation.",
    "SKIN_OR_DERMATOLOGY": "Skin and dermatology related consultation.",
    "WOMENS_OR_REPRODUCTIVE_HEALTH": "Women's health and reproductive health guidance.",
    "VACCINATIONS_AND_PREVENTIVE_SCREENINGS": "Use for vaccinations, immunizations, vaccine schedules or requirements, preventive screenings, and routine preventive medical checks. This includes questions about when vaccines are due, including school-related vaccine requirements. Not for general wellness tips or non-diagnostic health education.",
    "PEDIATRICS_OR_CHILD_HEALTH": "Pediatric and child health related consultation.",
    "OTHER_MEDICAL_CONCERN": "Other medical concerns not listed above.",
    "MEDICINE_DELIVERY": "Assist with OTC medication pickup or pharmacy navigation.",
    "MENTAL_WELLBEING_SUPPORT": "Use for explicit emotional or psychological support needs such as anxiety, depression, stress, panic, counseling, therapy, coping, loneliness, grief, or wanting someone to talk to. Do not use for physical pain, injury, mobility issues, or medical symptom evaluation unless the request is primarily about mental health or emotional support.",
    "MEDICATION_REMINDERS": "Use only for medication-taking reminders, schedules, alarms, or prompts for OTC medication or supplements. This category is about remembering to take medicine, not about sleep hygiene, bedtime routines, rest, wellness coaching, or broader health education.",
    "HEALTH_EDUCATION_GUIDANCE": "Use for general health information or wellness education such as hygiene, sleep hygiene, bedtime routines, rest, nutrition, healthy habits, preventive care education, and routine-care questions like when to get checkups or eye exams. Do not use for vaccinations or immunization schedules, and do not use when the person is asking for diagnosis, symptom evaluation, or a doctor/specialist consultation.",
    # Elderly & Community
    "ELDERLY_COMMUNITY_ASSISTANCE": "Parent category for elderly and community-related support.",
    "SENIOR_RELOCATION_SUPPORT": "Help seniors find housing and assist with the moving process.",
    "DIGITAL_SUPPORT_FOR_SENIORS": "Support with using phones, tablets, and apps.",
    "MEDICATION_MANAGEMENT": "Medication reminders or help organizing medications (non-clinical).",
    "MEDICAL_DEVICES_SETUP": "Help setting up or using medical devices at home (non-clinical).",
    "ERRANDS_EVENTS_TRANSPORTATION": "Assistance with errands or transport to events.",
    "TRANSPORTATION_APPOINTMENTS_EVENTS": "Transport to appointments, events, or other destinations.",
    "SCHEDULING_APPOINTMENTS_OR_TASKS": "Help scheduling appointments or organizing tasks.",
    "SOCIAL_CONNECTION": "Companionship and social activities (calls, walks, games).",
    "MEAL_SUPPORT": "Help cooking meals or prepping food based on dietary needs.",
}
