name: Python Flask CI Pipeline
on:
  push:
        branches: 
            - feature/divyatanwar/ai-ci-build
  pull_request:
        branches: 
            - feature/divyatanwar/ai-ci-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      - name: Install Python Virtual Environment
        run: pip3 install virtualenv
      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Virtual Environment
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      
      - name: Activate Virtual Environment and Install Packages
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 *.py --max-line-length=150

      - name: Run pytest
        run: |
          pytest

      - name: Pytest Code Coverage
        run: pytest --cov=myproj tests/
